# Generated by Django 5.0.2 on 2026-02-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_product_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='club',
            name='products',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
